project:
  type: website
  execute-dir: project
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!CONTRIBUTIONG.md"
    - "!LICENSE.md"

website:
  title: "Single-cell transcriptomics with Python"
  favicon: assets/SIB_logo.svg
  search: true
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: precourse_preparations.qmd
      - href: course_schedule.qmd
      - text: "day 1"
        menu:
          - href: "ipynb/day1-0_setup.ipynb"
          - href: "ipynb/day1-1_cellranger.ipynb"
          - href: "ipynb/day1-2_analysis_tools_qc.ipynb"
          - href: "ipynb/day1-3_normalization_scaling.ipynb"
      - text: "day 2"
        menu: 
          - href: "ipynb/day2-1_dimensionality_reduction.ipynb"
          - href: "ipynb/day2-2_integration.ipynb"
          - href: "ipynb/day2-3_clustering.ipynb"
          - href: "ipynb/day2-4_visualization.ipynb"
      - text: "day 3"
        menu:
          - href: "ipynb/day3-1_tf.ipynb"
          - href: "ipynb/day3-3_trajectory_analysis.ipynb"
          - href: "ipynb/day3-4_velocity1.ipynb"
          - href: "ipynb/day3-4_velocity2.ipynb"

    right:
      - icon: github
        href: https://github.com/sib-swiss/single-cell-python-training/
        aria-label: GitHub
  sidebar:
    logo: assets/SIB_LogoQ_GBv.svg

format:
  html:
    code-link: true
    theme: 
      - default
      - custom.scss
    toc: true
    header-includes: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">

execute:
  freeze: auto 
  cache: true
  tidy: true



